### ISSUE TITLE
Logout does not open the prompt

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu_session.dart#6]
```dart
  /// Request a logout dialog.
  Future<void> logout({Set<GnomeLogoutMode> mode = const {}}) {
    var logoutMode = 0;
    for (final flag in mode) {
      logoutMode |= flag.index;
    }
    return _object.callMethod(managerName, 'Logout', [DBusUint32(logoutMode)],
        replySignature: DBusSignature(''));
  }
```

the int 0 should open the prompt, however you are being logged out without a promt :)

logoutMode |= flag.index should not increase the value of logoutMode if the flag.index is 0 but it looks like 1 is being used for some reason

**Comment by d-loose** [comment]
I don't quite understand the problem, and it works fine for me.
Does `logout()` or `logout(mode: {GnomeLogoutMode.normal})` call the DBus API with the wrong parameter (i.e. `logoutMode = 1`), or does calling DBus with `logoutMode = 0` not give you a prompt?

**Comment by Feichtmeier** [comment]
When I use _session.logout() from another app (software) the logout dialog does not pop up but I am logged out directly.
When I looked up the code I found that 0 stands for the normal logout mode with a prompt however I assume that there is something not working and somehow 1 is used, which stands for directly log out (I think).

Calling the dbus method directly from d-feet with 0 as the argument it works
![grafik](https://user-images.githubusercontent.com/15329494/194849424-9b3927b8-b08c-488e-9738-d20196699466.png)

**Comment by d-loose** [comment]
I don't see how `logoutMode` would be set to a wrong value here (especially if you don't pass any parameters).
Do you call `logout()` directly on a `GnomeSessionManager` or do you use the `UbuntuSession` API? The latter calls systemd-logind's API (and doesn't give you any warnings) unless you pass `fallback: false` to the session object.

**Comment by Feichtmeier** [comment]
I use UbuntuSession.logout in a manner you added UbuntuSession.reboot assuming that it open the dialog as well
I might have looked up the wrong implementation, but I assumed that logout calls the dbus method in the end
But after re-reading https://github.com/ubuntu-flutter-community/software/pull/366 I understand the problem I think :)
To get the prompt I need the gnome session manager class?
Edit: trying...

**Comment by jpnurmi** [comment]
My expectation was that the common API would do the right thing because we want apps to support all possible DEs. :slightly_smiling_face:

**Comment by d-loose** [comment]
`UbuntuSession` tries to detect the current desktop environment (currently by simply checking `XDG_CURRENT_DESKTOP`, but I want to add more checks) and then calls the appropriate API. If it doesn't work, this means that `XDG_CURRENT_DESKTOP` is not set correctly (e.g. when running from VSCode..).

**Comment by jpnurmi** [comment]
Right! @Feichtmeier, could you try running the app outside VS Code, please? Electron sets `XDG_CURRENT_DESKTOP=unity` and VS Code leaks it to the child process.

**Comment by jpnurmi** [comment]
Even `neofetch` prints Unity if I run it from the built-in VS Code terminal...

**Comment by Feichtmeier** [comment]
Aha!

Yeah that is the problem, running the binary directy opens the prompt! Sorry for this issue then I was not aware of the exact desktop checking mechanism :P Thanks for your investigation

![grafik](https://user-images.githubusercontent.com/15329494/194858822-c8d815fe-ad4d-4563-82b1-d0e8bdd6acac.png)
